
1:
	g++-11 -g -Wall -pedantic -fmodules-ts signal_handler.cpp error_string.cpp explicit_enum.cpp exec_arg.cpp ./mmap/mmap_anon.cpp ./parent_dir/parent.cpp read_input.cpp prime_number.cpp -o parent
	g++-11 -g -Wall -pedantic -fmodules-ts signal_handler.cpp error_string.cpp explicit_enum.cpp exec_arg.cpp ./mmap/mmap_anon.cpp ./child_dir/child.cpp read_input.cpp prime_number.cpp -o child
2:
	g++-11 -g -Wall -pedantic -fmodules-ts signal_handler.cpp error_string.cpp explicit_enum.cpp exec_arg.cpp ./mmap/mmap_file.cpp ./parent_dir/parent_fd.cpp read_input.cpp prime_number.cpp -o parent
	g++-11 -g -Wall -pedantic -fmodules-ts signal_handler.cpp error_string.cpp explicit_enum.cpp exec_arg.cpp ./mmap/mmap_file.cpp ./child_dir/child_fd.cpp read_input.cpp prime_number.cpp -o child

